function sys = coraSystemsWrapper(systype, dt)
    switch(lower(systype))
        % Discretized continuous-time stirred tank reactor
        case 'cstr'
            fun = @(x,u) cstrDiscr(x,u,dt);

            dims = struct( ...
                'n', 2, ...
                'm', 2, ...
                'p', 2 ...
                );         
    end
    sys = struct( ...
        'fun', fun, ...
        'dims', dims ...
        );
end

