function sorted = sortData(plotdata, mode, i)
    switch mode
        case {'ddsf', 'u-ddsf'}
            ux = plotdata.u; ulx = plotdata.ul;
            sorted = struct( ...
                'u', ux(i, :, :), ...
                'ul', ulx(i, :, :) ...
                );
        case 'y-ddsf'
            yx = plotdata.y; ylx = plotdata.yl;
            sorted = struct( ...
                'y', yx(i, :, :), ...
                'yl', ylx(i, :, :) ...
                );
        case 'deepc'
            ux = plotdata.u; yx = plotdata.y;
            sorted = struct( ...
                'u', ux(i, :, :), ...
                'y', yx(i, :, :) ...
                );
        otherwise
            error('Unsupported mode: %s', mode);
    end
end
